steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.15.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.15.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      terraform plan
  env:
    - "TF_VAR_project_id=${PROJECT_ID}"
    - "TF_VAR_region=asia-southeast2"
    - "TF_VAR_branch=${BRANCH_NAME}"
# [END tf-plan]
# [START tf-apply]
#- id: 'tf apply'
#  name: 'hashicorp/terraform:0.15.0'
#  entrypoint: 'sh'
#  args: 
#  - '-c'
#  - | 
#        terraform apply -auto-approve
#  env:
#    - "TF_VAR_project_id=${PROJECT_ID}"
#    - "TF_VAR_region=asia-southeast2"
#    - "TF_VAR_branch=${BRANCH_NAME}"
#timeout: 720s
## [END tf-apply]
